---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-devspaces
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  channel: {{ .Values.channel }}
  installPlanApproval: Automatic
  name: openshift-devspaces
  source: redhat-operators
  sourceNamespace: openshift-marketplace